In [1]:
import os

print(os.getcwd())

/Users/manya17/Documents

In [3]:
import os

print(os.listdir())

['UMBC Bill-010226.pdf', 'CoverLetters', 'unofficial_Transcript.pdf', '.DS_Store', 'Eleti_602_HW12.ipynb', '.localized', 'Untitled.ipynb', 'Manya UMBC Balance.pdf', 'projects', 'Datasets', 'Resumes', 'I-20_Eleti_LakshmiManya.pdf', 'LME acc.pdf', 'Manya_GGT_Resume.docx', 'LakshmiManya_Eleti_Airbnb_Resume.docx', 'Your Electronic Receipt.pdf', 'WhatsApp.app', '.ipynb_checkpoints', 'Dava_602_HW12.ipynb', 'Analyzing_the_Effect_of_AI_Automation_F.key']

In [4]:
import os

print(os.listdir("projects"))

['.DS_Store', 'student_success_dashboard']

In [5]:
import os

print(os.listdir("projects/student_success_dashboard/data"))

['Most-Recent-Cohorts-Institution.csv']

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(
    "projects/student_success_dashboard/data/Most-Recent-Cohorts-Institution.csv",
    low_memory=False
)

In [8]:
df.shape

(6322, 3308)

In [9]:
df.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,MD_EARN_WNE_INC1_P11,MD_EARN_WNE_INC2_P11,MD_EARN_WNE_INC3_P11,MD_EARN_WNE_INDEP0_P11,MD_EARN_WNE_INDEP1_P11,MD_EARN_WNE_MALE0_P11,MD_EARN_WNE_MALE1_P11,SCORECARD_SECTOR,EARN_THR_STATE,EARN_THR_NAT
0,100654,100200.0,1002.0,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,36650.0,41070.0,47016.0,38892.0,41738.0,38167.0,40250.0,4,30168.0,32842
1,100663,105200.0,1052.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu/,https://tcc.ruffalonl.com/University of Alabam...,...,47182.0,51896.0,54368.0,50488.0,51505.0,46559.0,59181.0,4,30168.0,32842
2,100690,2503400.0,25034.0,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,https://www.amridgeuniversity.edu/,https://www2.amridgeuniversity.edu:9091/,...,35752.0,41007.0,NaN,NaN,38467.0,32654.0,49435.0,5,30168.0,32842
3,100706,105500.0,1055.0,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu/,uah.clearcostcalculator.com/student/default/ne...,...,51208.0,62219.0,62577.0,55920.0,60221.0,47787.0,67454.0,4,30168.0,32842
4,100724,100500.0,1005.0,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu/,tcc.ruffalonl.com/Alabama State University/Fre...,...,32844.0,36932.0,37966.0,34294.0,31797.0,32303.0,36964.0,4,30168.0,32842

In [10]:
for col in df.columns:
    print(col)

UNITID
OPEID
OPEID6
INSTNM
CITY
STABBR
ZIP
ACCREDAGENCY
INSTURL
NPCURL
SCH_DEG
HCM2
MAIN
NUMBRANCH
PREDDEG
HIGHDEG
CONTROL
ST_FIPS
REGION
LOCALE
LOCALE2
LATITUDE
LONGITUDE
CCBASIC
CCUGPROF
CCSIZSET
HBCU
PBI
ANNHI
TRIBAL
AANAPII
HSI
NANTI
MENONLY
WOMENONLY
RELAFFIL
ADM_RATE
ADM_RATE_ALL
SATVR25
SATVR75
SATMT25
SATMT75
SATWR25
SATWR75
SATVRMID
SATMTMID
SATWRMID
ACTCM25
ACTCM75
ACTEN25
ACTEN75
ACTMT25
ACTMT75
ACTWR25
ACTWR75
ACTCMMID
ACTENMID
ACTMTMID
ACTWRMID
SAT_AVG
SAT_AVG_ALL
PCIP01
PCIP03
PCIP04
PCIP05
PCIP09
PCIP10
PCIP11
PCIP12
PCIP13
PCIP14
PCIP15
PCIP16
PCIP19
PCIP22
PCIP23
PCIP24
PCIP25
PCIP26
PCIP27
PCIP29
PCIP30
PCIP31
PCIP38
PCIP39
PCIP40
PCIP41
PCIP42
PCIP43
PCIP44
PCIP45
PCIP46
PCIP47
PCIP48
PCIP49
PCIP50
PCIP51
PCIP52
PCIP54
CIP01CERT1
CIP01CERT2
CIP01ASSOC
CIP01CERT4
CIP01BACHL
CIP03CERT1
CIP03CERT2
CIP03ASSOC
CIP03CERT4
CIP03BACHL
CIP04CERT1
CIP04CERT2
CIP04ASSOC
CIP04CERT4
CIP04BACHL
CIP05CERT1
CIP05CERT2
CIP05ASSOC
CIP05CERT4
CIP05BACHL
CIP09CERT1
CIP09CERT2
CIP09ASSOC
CIP09CERT4
CIP09BACHL
CIP10CERT1
CIP10CERT2
CIP10ASSOC
CIP10CERT4
CIP10BACHL
CIP11CERT1
CIP11CERT2
CIP11ASSOC
CIP11CERT4
CIP11BACHL
CIP12CERT1
CIP12CERT2
CIP12ASSOC
CIP12CERT4
CIP12BACHL
CIP13CERT1
CIP13CERT2
CIP13ASSOC
CIP13CERT4
CIP13BACHL
CIP14CERT1
CIP14CERT2
CIP14ASSOC
CIP14CERT4
CIP14BACHL
CIP15CERT1
CIP15CERT2
CIP15ASSOC
CIP15CERT4
CIP15BACHL
CIP16CERT1
CIP16CERT2
CIP16ASSOC
CIP16CERT4
CIP16BACHL
CIP19CERT1
CIP19CERT2
CIP19ASSOC
CIP19CERT4
CIP19BACHL
CIP22CERT1
CIP22CERT2
CIP22ASSOC
CIP22CERT4
CIP22BACHL
CIP23CERT1
CIP23CERT2
CIP23ASSOC
CIP23CERT4
CIP23BACHL
CIP24CERT1
CIP24CERT2
CIP24ASSOC
CIP24CERT4
CIP24BACHL
CIP25CERT1
CIP25CERT2
CIP25ASSOC
CIP25CERT4
CIP25BACHL
CIP26CERT1
CIP26CERT2
CIP26ASSOC
CIP26CERT4
CIP26BACHL
CIP27CERT1
CIP27CERT2
CIP27ASSOC
CIP27CERT4
CIP27BACHL
CIP29CERT1
CIP29CERT2
CIP29ASSOC
CIP29CERT4
CIP29BACHL
CIP30CERT1
CIP30CERT2
CIP30ASSOC
CIP30CERT4
CIP30BACHL
CIP31CERT1
CIP31CERT2
CIP31ASSOC
CIP31CERT4
CIP31BACHL
CIP38CERT1
CIP38CERT2
CIP38ASSOC
CIP38CERT4
CIP38BACHL
CIP39CERT1
CIP39CERT2
CIP39ASSOC
CIP39CERT4
CIP39BACHL
CIP40CERT1
CIP40CERT2
CIP40ASSOC
CIP40CERT4
CIP40BACHL
CIP41CERT1
CIP41CERT2
CIP41ASSOC
CIP41CERT4
CIP41BACHL
CIP42CERT1
CIP42CERT2
CIP42ASSOC
CIP42CERT4
CIP42BACHL
CIP43CERT1
CIP43CERT2
CIP43ASSOC
CIP43CERT4
CIP43BACHL
CIP44CERT1
CIP44CERT2
CIP44ASSOC
CIP44CERT4
CIP44BACHL
CIP45CERT1
CIP45CERT2
CIP45ASSOC
CIP45CERT4
CIP45BACHL
CIP46CERT1
CIP46CERT2
CIP46ASSOC
CIP46CERT4
CIP46BACHL
CIP47CERT1
CIP47CERT2
CIP47ASSOC
CIP47CERT4
CIP47BACHL
CIP48CERT1
CIP48CERT2
CIP48ASSOC
CIP48CERT4
CIP48BACHL
CIP49CERT1
CIP49CERT2
CIP49ASSOC
CIP49CERT4
CIP49BACHL
CIP50CERT1
CIP50CERT2
CIP50ASSOC
CIP50CERT4
CIP50BACHL
CIP51CERT1
CIP51CERT2
CIP51ASSOC
CIP51CERT4
CIP51BACHL
CIP52CERT1
CIP52CERT2
CIP52ASSOC
CIP52CERT4
CIP52BACHL
CIP54CERT1
CIP54CERT2
CIP54ASSOC
CIP54CERT4
CIP54BACHL
DISTANCEONLY
UGDS
UG
UGDS_WHITE
UGDS_BLACK
UGDS_HISP
UGDS_ASIAN
UGDS_AIAN
UGDS_NHPI
UGDS_2MOR
UGDS_NRA
UGDS_UNKN
UGDS_WHITENH
UGDS_BLACKNH
UGDS_API
UGDS_AIANOLD
UGDS_HISPOLD
UG_NRA
UG_UNKN
UG_WHITENH
UG_BLACKNH
UG_API
UG_AIANOLD
UG_HISPOLD
PPTUG_EF
PPTUG_EF2
CURROPER
NPT4_PUB
NPT4_PRIV
NPT4_PROG
NPT4_OTHER
NPT41_PUB
NPT42_PUB
NPT43_PUB
NPT44_PUB
NPT45_PUB
NPT41_PRIV
NPT42_PRIV
NPT43_PRIV
NPT44_PRIV
NPT45_PRIV
NPT41_PROG
NPT42_PROG
NPT43_PROG
NPT44_PROG
NPT45_PROG
NPT41_OTHER
NPT42_OTHER
NPT43_OTHER
NPT44_OTHER
NPT45_OTHER
NPT4_048_PUB
NPT4_048_PRIV
NPT4_048_PROG
NPT4_048_OTHER
NPT4_3075_PUB
NPT4_3075_PRIV
NPT4_75UP_PUB
NPT4_75UP_PRIV
NPT4_3075_PROG
NPT4_3075_OTHER
NPT4_75UP_PROG
NPT4_75UP_OTHER
NUM4_PUB
NUM4_PRIV
NUM4_PROG
NUM4_OTHER
NUM41_PUB
NUM42_PUB
NUM43_PUB
NUM44_PUB
NUM45_PUB
NUM41_PRIV
NUM42_PRIV
NUM43_PRIV
NUM44_PRIV
NUM45_PRIV
NUM41_PROG
NUM42_PROG
NUM43_PROG
NUM44_PROG
NUM45_PROG
NUM41_OTHER
NUM42_OTHER
NUM43_OTHER
NUM44_OTHER
NUM45_OTHER
COSTT4_A
COSTT4_P
TUITIONFEE_IN
TUITIONFEE_OUT
TUITIONFEE_PROG
TUITFTE
INEXPFTE
AVGFACSAL
PFTFAC
PCTPELL
C150_4
C150_L4
C150_4_POOLED
C150_L4_POOLED
POOLYRS
PFTFTUG1_EF
D150_4
D150_L4
D150_4_POOLED
D150_L4_POOLED
C150_4_WHITE
C150_4_BLACK
C150_4_HISP
C150_4_ASIAN
C150_4_AIAN
C150_4_NHPI
C150_4_2MOR
C150_4_NRA
C150_4_UNKN
C150_4_WHITENH
C150_4_BLACKNH
C150_4_API
C150_4_AIANOLD
C150_4_HISPOLD
C150_L4_WHITE
C150_L4_BLACK
C150_L4_HISP
C150_L4_ASIAN
C150_L4_AIAN
C150_L4_NHPI
C150_L4_2MOR
C150_L4_NRA
C150_L4_UNKN
C150_L4_WHITENH
C150_L4_BLACKNH
C150_L4_API
C150_L4_AIANOLD
C150_L4_HISPOLD
C200_4
C200_L4
D200_4
D200_L4
RET_FT4
RET_FTL4
RET_PT4
RET_PTL4
C200_4_POOLED
C200_L4_POOLED
POOLYRS200
D200_4_POOLED
D200_L4_POOLED
PCTFLOAN
UG25ABV
CDR2
CDR3
DEATH_YR2_RT
COMP_ORIG_YR2_RT
COMP_4YR_TRANS_YR2_RT
COMP_2YR_TRANS_YR2_RT
WDRAW_ORIG_YR2_RT
WDRAW_4YR_TRANS_YR2_RT
WDRAW_2YR_TRANS_YR2_RT
ENRL_ORIG_YR2_RT
ENRL_4YR_TRANS_YR2_RT
ENRL_2YR_TRANS_YR2_RT
UNKN_ORIG_YR2_RT
UNKN_4YR_TRANS_YR2_RT
UNKN_2YR_TRANS_YR2_RT
LO_INC_DEATH_YR2_RT
LO_INC_COMP_ORIG_YR2_RT
LO_INC_COMP_4YR_TRANS_YR2_RT
LO_INC_COMP_2YR_TRANS_YR2_RT
LO_INC_WDRAW_ORIG_YR2_RT
LO_INC_WDRAW_4YR_TRANS_YR2_RT
LO_INC_WDRAW_2YR_TRANS_YR2_RT
LO_INC_ENRL_ORIG_YR2_RT
LO_INC_ENRL_4YR_TRANS_YR2_RT
LO_INC_ENRL_2YR_TRANS_YR2_RT
LO_INC_UNKN_ORIG_YR2_RT
LO_INC_UNKN_4YR_TRANS_YR2_RT
LO_INC_UNKN_2YR_TRANS_YR2_RT
MD_INC_DEATH_YR2_RT
MD_INC_COMP_ORIG_YR2_RT
MD_INC_COMP_4YR_TRANS_YR2_RT
MD_INC_COMP_2YR_TRANS_YR2_RT
MD_INC_WDRAW_ORIG_YR2_RT
MD_INC_WDRAW_4YR_TRANS_YR2_RT
MD_INC_WDRAW_2YR_TRANS_YR2_RT
MD_INC_ENRL_ORIG_YR2_RT
MD_INC_ENRL_4YR_TRANS_YR2_RT
MD_INC_ENRL_2YR_TRANS_YR2_RT
MD_INC_UNKN_ORIG_YR2_RT
MD_INC_UNKN_4YR_TRANS_YR2_RT
MD_INC_UNKN_2YR_TRANS_YR2_RT
HI_INC_DEATH_YR2_RT
HI_INC_COMP_ORIG_YR2_RT
HI_INC_COMP_4YR_TRANS_YR2_RT
HI_INC_COMP_2YR_TRANS_YR2_RT
HI_INC_WDRAW_ORIG_YR2_RT
HI_INC_WDRAW_4YR_TRANS_YR2_RT
HI_INC_WDRAW_2YR_TRANS_YR2_RT
HI_INC_ENRL_ORIG_YR2_RT
HI_INC_ENRL_4YR_TRANS_YR2_RT
HI_INC_ENRL_2YR_TRANS_YR2_RT
HI_INC_UNKN_ORIG_YR2_RT
HI_INC_UNKN_4YR_TRANS_YR2_RT
HI_INC_UNKN_2YR_TRANS_YR2_RT
DEP_DEATH_YR2_RT
DEP_COMP_ORIG_YR2_RT
DEP_COMP_4YR_TRANS_YR2_RT
DEP_COMP_2YR_TRANS_YR2_RT
DEP_WDRAW_ORIG_YR2_RT
DEP_WDRAW_4YR_TRANS_YR2_RT
DEP_WDRAW_2YR_TRANS_YR2_RT
DEP_ENRL_ORIG_YR2_RT
DEP_ENRL_4YR_TRANS_YR2_RT
DEP_ENRL_2YR_TRANS_YR2_RT
DEP_UNKN_ORIG_YR2_RT
DEP_UNKN_4YR_TRANS_YR2_RT
DEP_UNKN_2YR_TRANS_YR2_RT
IND_DEATH_YR2_RT
IND_COMP_ORIG_YR2_RT
IND_COMP_4YR_TRANS_YR2_RT
IND_COMP_2YR_TRANS_YR2_RT
IND_WDRAW_ORIG_YR2_RT
IND_WDRAW_4YR_TRANS_YR2_RT
IND_WDRAW_2YR_TRANS_YR2_RT
IND_ENRL_ORIG_YR2_RT
IND_ENRL_4YR_TRANS_YR2_RT
IND_ENRL_2YR_TRANS_YR2_RT
IND_UNKN_ORIG_YR2_RT
IND_UNKN_4YR_TRANS_YR2_RT
IND_UNKN_2YR_TRANS_YR2_RT
FEMALE_DEATH_YR2_RT
FEMALE_COMP_ORIG_YR2_RT
FEMALE_COMP_4YR_TRANS_YR2_RT
FEMALE_COMP_2YR_TRANS_YR2_RT
FEMALE_WDRAW_ORIG_YR2_RT
FEMALE_WDRAW_4YR_TRANS_YR2_RT
FEMALE_WDRAW_2YR_TRANS_YR2_RT
FEMALE_ENRL_ORIG_YR2_RT
FEMALE_ENRL_4YR_TRANS_YR2_RT
FEMALE_ENRL_2YR_TRANS_YR2_RT
FEMALE_UNKN_ORIG_YR2_RT
FEMALE_UNKN_4YR_TRANS_YR2_RT
FEMALE_UNKN_2YR_TRANS_YR2_RT
MALE_DEATH_YR2_RT
MALE_COMP_ORIG_YR2_RT
MALE_COMP_4YR_TRANS_YR2_RT
MALE_COMP_2YR_TRANS_YR2_RT
MALE_WDRAW_ORIG_YR2_RT
MALE_WDRAW_4YR_TRANS_YR2_RT
MALE_WDRAW_2YR_TRANS_YR2_RT
MALE_ENRL_ORIG_YR2_RT
MALE_ENRL_4YR_TRANS_YR2_RT
MALE_ENRL_2YR_TRANS_YR2_RT
MALE_UNKN_ORIG_YR2_RT
MALE_UNKN_4YR_TRANS_YR2_RT
MALE_UNKN_2YR_TRANS_YR2_RT
PELL_DEATH_YR2_RT
PELL_COMP_ORIG_YR2_RT
PELL_COMP_4YR_TRANS_YR2_RT
PELL_COMP_2YR_TRANS_YR2_RT
PELL_WDRAW_ORIG_YR2_RT
PELL_WDRAW_4YR_TRANS_YR2_RT
PELL_WDRAW_2YR_TRANS_YR2_RT
PELL_ENRL_ORIG_YR2_RT
PELL_ENRL_4YR_TRANS_YR2_RT
PELL_ENRL_2YR_TRANS_YR2_RT
PELL_UNKN_ORIG_YR2_RT
PELL_UNKN_4YR_TRANS_YR2_RT
PELL_UNKN_2YR_TRANS_YR2_RT
NOPELL_DEATH_YR2_RT
NOPELL_COMP_ORIG_YR2_RT
NOPELL_COMP_4YR_TRANS_YR2_RT
NOPELL_COMP_2YR_TRANS_YR2_RT
NOPELL_WDRAW_ORIG_YR2_RT
NOPELL_WDRAW_4YR_TRANS_YR2_RT
NOPELL_WDRAW_2YR_TRANS_YR2_RT
NOPELL_ENRL_ORIG_YR2_RT
NOPELL_ENRL_4YR_TRANS_YR2_RT
NOPELL_ENRL_2YR_TRANS_YR2_RT
NOPELL_UNKN_ORIG_YR2_RT
NOPELL_UNKN_4YR_TRANS_YR2_RT
NOPELL_UNKN_2YR_TRANS_YR2_RT
LOAN_DEATH_YR2_RT
LOAN_COMP_ORIG_YR2_RT
LOAN_COMP_4YR_TRANS_YR2_RT
LOAN_COMP_2YR_TRANS_YR2_RT
LOAN_WDRAW_ORIG_YR2_RT
LOAN_WDRAW_4YR_TRANS_YR2_RT
LOAN_WDRAW_2YR_TRANS_YR2_RT
LOAN_ENRL_ORIG_YR2_RT
LOAN_ENRL_4YR_TRANS_YR2_RT
LOAN_ENRL_2YR_TRANS_YR2_RT
LOAN_UNKN_ORIG_YR2_RT
LOAN_UNKN_4YR_TRANS_YR2_RT
LOAN_UNKN_2YR_TRANS_YR2_RT
NOLOAN_DEATH_YR2_RT
NOLOAN_COMP_ORIG_YR2_RT
NOLOAN_COMP_4YR_TRANS_YR2_RT
NOLOAN_COMP_2YR_TRANS_YR2_RT
NOLOAN_WDRAW_ORIG_YR2_RT
NOLOAN_WDRAW_4YR_TRANS_YR2_RT
NOLOAN_WDRAW_2YR_TRANS_YR2_RT
NOLOAN_ENRL_ORIG_YR2_RT
NOLOAN_ENRL_4YR_TRANS_YR2_RT
NOLOAN_ENRL_2YR_TRANS_YR2_RT
NOLOAN_UNKN_ORIG_YR2_RT
NOLOAN_UNKN_4YR_TRANS_YR2_RT
NOLOAN_UNKN_2YR_TRANS_YR2_RT
FIRSTGEN_DEATH_YR2_RT
FIRSTGEN_COMP_ORIG_YR2_RT
FIRSTGEN_COMP_4YR_TRANS_YR2_RT
FIRSTGEN_COMP_2YR_TRANS_YR2_RT
FIRSTGEN_WDRAW_ORIG_YR2_RT
FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT
FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT
FIRSTGEN_ENRL_ORIG_YR2_RT
FIRSTGEN_ENRL_4YR_TRANS_YR2_RT
FIRSTGEN_ENRL_2YR_TRANS_YR2_RT
FIRSTGEN_UNKN_ORIG_YR2_RT
FIRSTGEN_UNKN_4YR_TRANS_YR2_RT
FIRSTGEN_UNKN_2YR_TRANS_YR2_RT
NOT1STGEN_DEATH_YR2_RT
NOT1STGEN_COMP_ORIG_YR2_RT
NOT1STGEN_COMP_4YR_TRANS_YR2_RT
NOT1STGEN_COMP_2YR_TRANS_YR2_RT
NOT1STGEN_WDRAW_ORIG_YR2_RT
NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT
NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT
NOT1STGEN_ENRL_ORIG_YR2_RT
NOT1STGEN_ENRL_4YR_TRANS_YR2_RT
NOT1STGEN_ENRL_2YR_TRANS_YR2_RT
NOT1STGEN_UNKN_ORIG_YR2_RT
NOT1STGEN_UNKN_4YR_TRANS_YR2_RT
NOT1STGEN_UNKN_2YR_TRANS_YR2_RT
DEATH_YR3_RT
COMP_ORIG_YR3_RT
COMP_4YR_TRANS_YR3_RT
COMP_2YR_TRANS_YR3_RT
WDRAW_ORIG_YR3_RT
WDRAW_4YR_TRANS_YR3_RT
WDRAW_2YR_TRANS_YR3_RT
ENRL_ORIG_YR3_RT
ENRL_4YR_TRANS_YR3_RT
ENRL_2YR_TRANS_YR3_RT
UNKN_ORIG_YR3_RT
UNKN_4YR_TRANS_YR3_RT
UNKN_2YR_TRANS_YR3_RT
LO_INC_DEATH_YR3_RT
LO_INC_COMP_ORIG_YR3_RT
LO_INC_COMP_4YR_TRANS_YR3_RT
LO_INC_COMP_2YR_TRANS_YR3_RT
LO_INC_WDRAW_ORIG_YR3_RT
LO_INC_WDRAW_4YR_TRANS_YR3_RT
LO_INC_WDRAW_2YR_TRANS_YR3_RT
LO_INC_ENRL_ORIG_YR3_RT
LO_INC_ENRL_4YR_TRANS_YR3_RT
LO_INC_ENRL_2YR_TRANS_YR3_RT
LO_INC_UNKN_ORIG_YR3_RT
LO_INC_UNKN_4YR_TRANS_YR3_RT
LO_INC_UNKN_2YR_TRANS_YR3_RT
MD_INC_DEATH_YR3_RT
MD_INC_COMP_ORIG_YR3_RT
MD_INC_COMP_4YR_TRANS_YR3_RT
MD_INC_COMP_2YR_TRANS_YR3_RT
MD_INC_WDRAW_ORIG_YR3_RT
MD_INC_WDRAW_4YR_TRANS_YR3_RT
MD_INC_WDRAW_2YR_TRANS_YR3_RT
MD_INC_ENRL_ORIG_YR3_RT
MD_INC_ENRL_4YR_TRANS_YR3_RT
MD_INC_ENRL_2YR_TRANS_YR3_RT
MD_INC_UNKN_ORIG_YR3_RT
MD_INC_UNKN_4YR_TRANS_YR3_RT
MD_INC_UNKN_2YR_TRANS_YR3_RT
HI_INC_DEATH_YR3_RT
HI_INC_COMP_ORIG_YR3_RT
HI_INC_COMP_4YR_TRANS_YR3_RT
HI_INC_COMP_2YR_TRANS_YR3_RT
HI_INC_WDRAW_ORIG_YR3_RT
HI_INC_WDRAW_4YR_TRANS_YR3_RT
HI_INC_WDRAW_2YR_TRANS_YR3_RT
HI_INC_ENRL_ORIG_YR3_RT
HI_INC_ENRL_4YR_TRANS_YR3_RT
HI_INC_ENRL_2YR_TRANS_YR3_RT
HI_INC_UNKN_ORIG_YR3_RT
HI_INC_UNKN_4YR_TRANS_YR3_RT
HI_INC_UNKN_2YR_TRANS_YR3_RT
DEP_DEATH_YR3_RT
DEP_COMP_ORIG_YR3_RT
DEP_COMP_4YR_TRANS_YR3_RT
DEP_COMP_2YR_TRANS_YR3_RT
DEP_WDRAW_ORIG_YR3_RT
DEP_WDRAW_4YR_TRANS_YR3_RT
DEP_WDRAW_2YR_TRANS_YR3_RT
DEP_ENRL_ORIG_YR3_RT
DEP_ENRL_4YR_TRANS_YR3_RT
DEP_ENRL_2YR_TRANS_YR3_RT
DEP_UNKN_ORIG_YR3_RT
DEP_UNKN_4YR_TRANS_YR3_RT
DEP_UNKN_2YR_TRANS_YR3_RT
IND_DEATH_YR3_RT
IND_COMP_ORIG_YR3_RT
IND_COMP_4YR_TRANS_YR3_RT
IND_COMP_2YR_TRANS_YR3_RT
IND_WDRAW_ORIG_YR3_RT
IND_WDRAW_4YR_TRANS_YR3_RT
IND_WDRAW_2YR_TRANS_YR3_RT
IND_ENRL_ORIG_YR3_RT
IND_ENRL_4YR_TRANS_YR3_RT
IND_ENRL_2YR_TRANS_YR3_RT
IND_UNKN_ORIG_YR3_RT
IND_UNKN_4YR_TRANS_YR3_RT
IND_UNKN_2YR_TRANS_YR3_RT
FEMALE_DEATH_YR3_RT
FEMALE_COMP_ORIG_YR3_RT
FEMALE_COMP_4YR_TRANS_YR3_RT
FEMALE_COMP_2YR_TRANS_YR3_RT
FEMALE_WDRAW_ORIG_YR3_RT
FEMALE_WDRAW_4YR_TRANS_YR3_RT
FEMALE_WDRAW_2YR_TRANS_YR3_RT
FEMALE_ENRL_ORIG_YR3_RT
FEMALE_ENRL_4YR_TRANS_YR3_RT
FEMALE_ENRL_2YR_TRANS_YR3_RT
FEMALE_UNKN_ORIG_YR3_RT
FEMALE_UNKN_4YR_TRANS_YR3_RT
FEMALE_UNKN_2YR_TRANS_YR3_RT
MALE_DEATH_YR3_RT
MALE_COMP_ORIG_YR3_RT
MALE_COMP_4YR_TRANS_YR3_RT
MALE_COMP_2YR_TRANS_YR3_RT
MALE_WDRAW_ORIG_YR3_RT
MALE_WDRAW_4YR_TRANS_YR3_RT
MALE_WDRAW_2YR_TRANS_YR3_RT
MALE_ENRL_ORIG_YR3_RT
MALE_ENRL_4YR_TRANS_YR3_RT
MALE_ENRL_2YR_TRANS_YR3_RT
MALE_UNKN_ORIG_YR3_RT
MALE_UNKN_4YR_TRANS_YR3_RT
MALE_UNKN_2YR_TRANS_YR3_RT
PELL_DEATH_YR3_RT
PELL_COMP_ORIG_YR3_RT
PELL_COMP_4YR_TRANS_YR3_RT
PELL_COMP_2YR_TRANS_YR3_RT
PELL_WDRAW_ORIG_YR3_RT
PELL_WDRAW_4YR_TRANS_YR3_RT
PELL_WDRAW_2YR_TRANS_YR3_RT
PELL_ENRL_ORIG_YR3_RT
PELL_ENRL_4YR_TRANS_YR3_RT
PELL_ENRL_2YR_TRANS_YR3_RT
PELL_UNKN_ORIG_YR3_RT
PELL_UNKN_4YR_TRANS_YR3_RT
PELL_UNKN_2YR_TRANS_YR3_RT
NOPELL_DEATH_YR3_RT
NOPELL_COMP_ORIG_YR3_RT
NOPELL_COMP_4YR_TRANS_YR3_RT
NOPELL_COMP_2YR_TRANS_YR3_RT
NOPELL_WDRAW_ORIG_YR3_RT
NOPELL_WDRAW_4YR_TRANS_YR3_RT
NOPELL_WDRAW_2YR_TRANS_YR3_RT
NOPELL_ENRL_ORIG_YR3_RT
NOPELL_ENRL_4YR_TRANS_YR3_RT
NOPELL_ENRL_2YR_TRANS_YR3_RT
NOPELL_UNKN_ORIG_YR3_RT
NOPELL_UNKN_4YR_TRANS_YR3_RT
NOPELL_UNKN_2YR_TRANS_YR3_RT
LOAN_DEATH_YR3_RT
LOAN_COMP_ORIG_YR3_RT
LOAN_COMP_4YR_TRANS_YR3_RT
LOAN_COMP_2YR_TRANS_YR3_RT
LOAN_WDRAW_ORIG_YR3_RT
LOAN_WDRAW_4YR_TRANS_YR3_RT
LOAN_WDRAW_2YR_TRANS_YR3_RT
LOAN_ENRL_ORIG_YR3_RT
LOAN_ENRL_4YR_TRANS_YR3_RT
LOAN_ENRL_2YR_TRANS_YR3_RT
LOAN_UNKN_ORIG_YR3_RT
LOAN_UNKN_4YR_TRANS_YR3_RT
LOAN_UNKN_2YR_TRANS_YR3_RT
NOLOAN_DEATH_YR3_RT
NOLOAN_COMP_ORIG_YR3_RT
NOLOAN_COMP_4YR_TRANS_YR3_RT
NOLOAN_COMP_2YR_TRANS_YR3_RT
NOLOAN_WDRAW_ORIG_YR3_RT
NOLOAN_WDRAW_4YR_TRANS_YR3_RT
NOLOAN_WDRAW_2YR_TRANS_YR3_RT
NOLOAN_ENRL_ORIG_YR3_RT
NOLOAN_ENRL_4YR_TRANS_YR3_RT
NOLOAN_ENRL_2YR_TRANS_YR3_RT
NOLOAN_UNKN_ORIG_YR3_RT
NOLOAN_UNKN_4YR_TRANS_YR3_RT
NOLOAN_UNKN_2YR_TRANS_YR3_RT
FIRSTGEN_DEATH_YR3_RT
FIRSTGEN_COMP_ORIG_YR3_RT
FIRSTGEN_COMP_4YR_TRANS_YR3_RT
FIRSTGEN_COMP_2YR_TRANS_YR3_RT
FIRSTGEN_WDRAW_ORIG_YR3_RT
FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT
FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT
FIRSTGEN_ENRL_ORIG_YR3_RT
FIRSTGEN_ENRL_4YR_TRANS_YR3_RT
FIRSTGEN_ENRL_2YR_TRANS_YR3_RT
FIRSTGEN_UNKN_ORIG_YR3_RT
FIRSTGEN_UNKN_4YR_TRANS_YR3_RT
FIRSTGEN_UNKN_2YR_TRANS_YR3_RT
NOT1STGEN_DEATH_YR3_RT
NOT1STGEN_COMP_ORIG_YR3_RT
NOT1STGEN_COMP_4YR_TRANS_YR3_RT
NOT1STGEN_COMP_2YR_TRANS_YR3_RT
NOT1STGEN_WDRAW_ORIG_YR3_RT
NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT
NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT
NOT1STGEN_ENRL_ORIG_YR3_RT
NOT1STGEN_ENRL_4YR_TRANS_YR3_RT
NOT1STGEN_ENRL_2YR_TRANS_YR3_RT
NOT1STGEN_UNKN_ORIG_YR3_RT
NOT1STGEN_UNKN_4YR_TRANS_YR3_RT
NOT1STGEN_UNKN_2YR_TRANS_YR3_RT
DEATH_YR4_RT
COMP_ORIG_YR4_RT
COMP_4YR_TRANS_YR4_RT
COMP_2YR_TRANS_YR4_RT
WDRAW_ORIG_YR4_RT
WDRAW_4YR_TRANS_YR4_RT
WDRAW_2YR_TRANS_YR4_RT
ENRL_ORIG_YR4_RT
ENRL_4YR_TRANS_YR4_RT
ENRL_2YR_TRANS_YR4_RT
UNKN_ORIG_YR4_RT
UNKN_4YR_TRANS_YR4_RT
UNKN_2YR_TRANS_YR4_RT
LO_INC_DEATH_YR4_RT
LO_INC_COMP_ORIG_YR4_RT
LO_INC_COMP_4YR_TRANS_YR4_RT
LO_INC_COMP_2YR_TRANS_YR4_RT
LO_INC_WDRAW_ORIG_YR4_RT
LO_INC_WDRAW_4YR_TRANS_YR4_RT
LO_INC_WDRAW_2YR_TRANS_YR4_RT
LO_INC_ENRL_ORIG_YR4_RT
LO_INC_ENRL_4YR_TRANS_YR4_RT
LO_INC_ENRL_2YR_TRANS_YR4_RT
LO_INC_UNKN_ORIG_YR4_RT
LO_INC_UNKN_4YR_TRANS_YR4_RT
LO_INC_UNKN_2YR_TRANS_YR4_RT
MD_INC_DEATH_YR4_RT
MD_INC_COMP_ORIG_YR4_RT
MD_INC_COMP_4YR_TRANS_YR4_RT
MD_INC_COMP_2YR_TRANS_YR4_RT
MD_INC_WDRAW_ORIG_YR4_RT
MD_INC_WDRAW_4YR_TRANS_YR4_RT
MD_INC_WDRAW_2YR_TRANS_YR4_RT
MD_INC_ENRL_ORIG_YR4_RT
MD_INC_ENRL_4YR_TRANS_YR4_RT
MD_INC_ENRL_2YR_TRANS_YR4_RT
MD_INC_UNKN_ORIG_YR4_RT
MD_INC_UNKN_4YR_TRANS_YR4_RT
MD_INC_UNKN_2YR_TRANS_YR4_RT
HI_INC_DEATH_YR4_RT
HI_INC_COMP_ORIG_YR4_RT
HI_INC_COMP_4YR_TRANS_YR4_RT
HI_INC_COMP_2YR_TRANS_YR4_RT
HI_INC_WDRAW_ORIG_YR4_RT
HI_INC_WDRAW_4YR_TRANS_YR4_RT
HI_INC_WDRAW_2YR_TRANS_YR4_RT
HI_INC_ENRL_ORIG_YR4_RT
HI_INC_ENRL_4YR_TRANS_YR4_RT
HI_INC_ENRL_2YR_TRANS_YR4_RT
HI_INC_UNKN_ORIG_YR4_RT
HI_INC_UNKN_4YR_TRANS_YR4_RT
HI_INC_UNKN_2YR_TRANS_YR4_RT
DEP_DEATH_YR4_RT
DEP_COMP_ORIG_YR4_RT
DEP_COMP_4YR_TRANS_YR4_RT
DEP_COMP_2YR_TRANS_YR4_RT
DEP_WDRAW_ORIG_YR4_RT
DEP_WDRAW_4YR_TRANS_YR4_RT
DEP_WDRAW_2YR_TRANS_YR4_RT
DEP_ENRL_ORIG_YR4_RT
DEP_ENRL_4YR_TRANS_YR4_RT
DEP_ENRL_2YR_TRANS_YR4_RT
DEP_UNKN_ORIG_YR4_RT
DEP_UNKN_4YR_TRANS_YR4_RT
DEP_UNKN_2YR_TRANS_YR4_RT
IND_DEATH_YR4_RT
IND_COMP_ORIG_YR4_RT
IND_COMP_4YR_TRANS_YR4_RT
IND_COMP_2YR_TRANS_YR4_RT
IND_WDRAW_ORIG_YR4_RT
IND_WDRAW_4YR_TRANS_YR4_RT
IND_WDRAW_2YR_TRANS_YR4_RT
IND_ENRL_ORIG_YR4_RT
IND_ENRL_4YR_TRANS_YR4_RT
IND_ENRL_2YR_TRANS_YR4_RT
IND_UNKN_ORIG_YR4_RT
IND_UNKN_4YR_TRANS_YR4_RT
IND_UNKN_2YR_TRANS_YR4_RT
FEMALE_DEATH_YR4_RT
FEMALE_COMP_ORIG_YR4_RT
FEMALE_COMP_4YR_TRANS_YR4_RT
FEMALE_COMP_2YR_TRANS_YR4_RT
FEMALE_WDRAW_ORIG_YR4_RT
FEMALE_WDRAW_4YR_TRANS_YR4_RT
FEMALE_WDRAW_2YR_TRANS_YR4_RT
FEMALE_ENRL_ORIG_YR4_RT
FEMALE_ENRL_4YR_TRANS_YR4_RT
FEMALE_ENRL_2YR_TRANS_YR4_RT
FEMALE_UNKN_ORIG_YR4_RT
FEMALE_UNKN_4YR_TRANS_YR4_RT
FEMALE_UNKN_2YR_TRANS_YR4_RT
MALE_DEATH_YR4_RT
MALE_COMP_ORIG_YR4_RT
MALE_COMP_4YR_TRANS_YR4_RT
MALE_COMP_2YR_TRANS_YR4_RT
MALE_WDRAW_ORIG_YR4_RT
MALE_WDRAW_4YR_TRANS_YR4_RT
MALE_WDRAW_2YR_TRANS_YR4_RT
MALE_ENRL_ORIG_YR4_RT
MALE_ENRL_4YR_TRANS_YR4_RT
MALE_ENRL_2YR_TRANS_YR4_RT
MALE_UNKN_ORIG_YR4_RT
MALE_UNKN_4YR_TRANS_YR4_RT
MALE_UNKN_2YR_TRANS_YR4_RT
PELL_DEATH_YR4_RT
PELL_COMP_ORIG_YR4_RT
PELL_COMP_4YR_TRANS_YR4_RT
PELL_COMP_2YR_TRANS_YR4_RT
PELL_WDRAW_ORIG_YR4_RT
PELL_WDRAW_4YR_TRANS_YR4_RT
PELL_WDRAW_2YR_TRANS_YR4_RT
PELL_ENRL_ORIG_YR4_RT
PELL_ENRL_4YR_TRANS_YR4_RT
PELL_ENRL_2YR_TRANS_YR4_RT
PELL_UNKN_ORIG_YR4_RT
PELL_UNKN_4YR_TRANS_YR4_RT
PELL_UNKN_2YR_TRANS_YR4_RT
NOPELL_DEATH_YR4_RT
NOPELL_COMP_ORIG_YR4_RT
NOPELL_COMP_4YR_TRANS_YR4_RT
NOPELL_COMP_2YR_TRANS_YR4_RT
NOPELL_WDRAW_ORIG_YR4_RT
NOPELL_WDRAW_4YR_TRANS_YR4_RT
NOPELL_WDRAW_2YR_TRANS_YR4_RT
NOPELL_ENRL_ORIG_YR4_RT
NOPELL_ENRL_4YR_TRANS_YR4_RT
NOPELL_ENRL_2YR_TRANS_YR4_RT
NOPELL_UNKN_ORIG_YR4_RT
NOPELL_UNKN_4YR_TRANS_YR4_RT
NOPELL_UNKN_2YR_TRANS_YR4_RT
LOAN_DEATH_YR4_RT
LOAN_COMP_ORIG_YR4_RT
LOAN_COMP_4YR_TRANS_YR4_RT
LOAN_COMP_2YR_TRANS_YR4_RT
LOAN_WDRAW_ORIG_YR4_RT
LOAN_WDRAW_4YR_TRANS_YR4_RT
LOAN_WDRAW_2YR_TRANS_YR4_RT
LOAN_ENRL_ORIG_YR4_RT
LOAN_ENRL_4YR_TRANS_YR4_RT
LOAN_ENRL_2YR_TRANS_YR4_RT
LOAN_UNKN_ORIG_YR4_RT
LOAN_UNKN_4YR_TRANS_YR4_RT
LOAN_UNKN_2YR_TRANS_YR4_RT
NOLOAN_DEATH_YR4_RT
NOLOAN_COMP_ORIG_YR4_RT
NOLOAN_COMP_4YR_TRANS_YR4_RT
NOLOAN_COMP_2YR_TRANS_YR4_RT
NOLOAN_WDRAW_ORIG_YR4_RT
NOLOAN_WDRAW_4YR_TRANS_YR4_RT
NOLOAN_WDRAW_2YR_TRANS_YR4_RT
NOLOAN_ENRL_ORIG_YR4_RT
NOLOAN_ENRL_4YR_TRANS_YR4_RT
NOLOAN_ENRL_2YR_TRANS_YR4_RT
NOLOAN_UNKN_ORIG_YR4_RT
NOLOAN_UNKN_4YR_TRANS_YR4_RT
NOLOAN_UNKN_2YR_TRANS_YR4_RT
FIRSTGEN_DEATH_YR4_RT
FIRSTGEN_COMP_ORIG_YR4_RT
FIRSTGEN_COMP_4YR_TRANS_YR4_RT
FIRSTGEN_COMP_2YR_TRANS_YR4_RT
FIRSTGEN_WDRAW_ORIG_YR4_RT
FIRSTGEN_WDRAW_4YR_TRANS_YR4_RT
FIRSTGEN_WDRAW_2YR_TRANS_YR4_RT
FIRSTGEN_ENRL_ORIG_YR4_RT
FIRSTGEN_ENRL_4YR_TRANS_YR4_RT
FIRSTGEN_ENRL_2YR_TRANS_YR4_RT
FIRSTGEN_UNKN_ORIG_YR4_RT
FIRSTGEN_UNKN_4YR_TRANS_YR4_RT
FIRSTGEN_UNKN_2YR_TRANS_YR4_RT
NOT1STGEN_DEATH_YR4_RT
NOT1STGEN_COMP_ORIG_YR4_RT
NOT1STGEN_COMP_4YR_TRANS_YR4_RT
NOT1STGEN_COMP_2YR_TRANS_YR4_RT
NOT1STGEN_WDRAW_ORIG_YR4_RT
NOT1STGEN_WDRAW_4YR_TRANS_YR4_RT
NOT1STGEN_WDRAW_2YR_TRANS_YR4_RT
NOT1STGEN_ENRL_ORIG_YR4_RT
NOT1STGEN_ENRL_4YR_TRANS_YR4_RT
NOT1STGEN_ENRL_2YR_TRANS_YR4_RT
NOT1STGEN_UNKN_ORIG_YR4_RT
NOT1STGEN_UNKN_4YR_TRANS_YR4_RT
NOT1STGEN_UNKN_2YR_TRANS_YR4_RT
DEATH_YR6_RT
COMP_ORIG_YR6_RT
COMP_4YR_TRANS_YR6_RT
COMP_2YR_TRANS_YR6_RT
WDRAW_ORIG_YR6_RT
WDRAW_4YR_TRANS_YR6_RT
WDRAW_2YR_TRANS_YR6_RT
ENRL_ORIG_YR6_RT
ENRL_4YR_TRANS_YR6_RT
ENRL_2YR_TRANS_YR6_RT
UNKN_ORIG_YR6_RT
UNKN_4YR_TRANS_YR6_RT
UNKN_2YR_TRANS_YR6_RT
LO_INC_DEATH_YR6_RT
LO_INC_COMP_ORIG_YR6_RT
LO_INC_COMP_4YR_TRANS_YR6_RT
LO_INC_COMP_2YR_TRANS_YR6_RT
LO_INC_WDRAW_ORIG_YR6_RT
LO_INC_WDRAW_4YR_TRANS_YR6_RT
LO_INC_WDRAW_2YR_TRANS_YR6_RT
LO_INC_ENRL_ORIG_YR6_RT
LO_INC_ENRL_4YR_TRANS_YR6_RT
LO_INC_ENRL_2YR_TRANS_YR6_RT
LO_INC_UNKN_ORIG_YR6_RT
LO_INC_UNKN_4YR_TRANS_YR6_RT
LO_INC_UNKN_2YR_TRANS_YR6_RT
MD_INC_DEATH_YR6_RT
MD_INC_COMP_ORIG_YR6_RT
MD_INC_COMP_4YR_TRANS_YR6_RT
MD_INC_COMP_2YR_TRANS_YR6_RT
MD_INC_WDRAW_ORIG_YR6_RT
MD_INC_WDRAW_4YR_TRANS_YR6_RT
MD_INC_WDRAW_2YR_TRANS_YR6_RT
MD_INC_ENRL_ORIG_YR6_RT
MD_INC_ENRL_4YR_TRANS_YR6_RT
MD_INC_ENRL_2YR_TRANS_YR6_RT
MD_INC_UNKN_ORIG_YR6_RT
MD_INC_UNKN_4YR_TRANS_YR6_RT
MD_INC_UNKN_2YR_TRANS_YR6_RT
HI_INC_DEATH_YR6_RT
HI_INC_COMP_ORIG_YR6_RT
HI_INC_COMP_4YR_TRANS_YR6_RT
HI_INC_COMP_2YR_TRANS_YR6_RT
HI_INC_WDRAW_ORIG_YR6_RT
HI_INC_WDRAW_4YR_TRANS_YR6_RT
HI_INC_WDRAW_2YR_TRANS_YR6_RT
HI_INC_ENRL_ORIG_YR6_RT
HI_INC_ENRL_4YR_TRANS_YR6_RT
HI_INC_ENRL_2YR_TRANS_YR6_RT

In [12]:
[col for col in df.columns if "UGDS" in col]

['UGDS',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'UGDS_WHITENH',
 'UGDS_BLACKNH',
 'UGDS_API',
 'UGDS_AIANOLD',
 'UGDS_HISPOLD',
 'UGDS_MEN',
 'UGDS_WOMEN']

In [13]:
[col for col in df.columns if "RET" in col]

['RET_FT4',
 'RET_FTL4',
 'RET_PT4',
 'RET_PTL4',
 'RET_FT4_POOLED',
 'RET_FTL4_POOLED',
 'RET_PT4_POOLED',
 'RET_PTL4_POOLED',
 'RET_FT_DEN4_POOLED',
 'RET_FT_DENL4_POOLED',
 'RET_PT_DEN4_POOLED',
 'RET_PT_DENL4_POOLED',
 'POOLYRSRET_FT',
 'POOLYRSRET_PT',
 'RET_FT4_POOLED_SUPP',
 'RET_FTL4_POOLED_SUPP',
 'RET_PT4_POOLED_SUPP',
 'RET_PTL4_POOLED_SUPP']

In [14]:
[col for col in df.columns if "C150" in col]

['C150_4',
 'C150_L4',
 'C150_4_POOLED',
 'C150_L4_POOLED',
 'C150_4_WHITE',
 'C150_4_BLACK',
 'C150_4_HISP',
 'C150_4_ASIAN',
 'C150_4_AIAN',
 'C150_4_NHPI',
 'C150_4_2MOR',
 'C150_4_NRA',
 'C150_4_UNKN',
 'C150_4_WHITENH',
 'C150_4_BLACKNH',
 'C150_4_API',
 'C150_4_AIANOLD',
 'C150_4_HISPOLD',
 'C150_L4_WHITE',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_ASIAN',
 'C150_L4_AIAN',
 'C150_L4_NHPI',
 'C150_L4_2MOR',
 'C150_L4_NRA',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_BLACKNH',
 'C150_L4_API',
 'C150_L4_AIANOLD',
 'C150_L4_HISPOLD',
 'C150_L4_POOLED_SUPP',
 'C150_4_POOLED_SUPP',
 'C150_4_PELL',
 'C150_L4_PELL',
 'C150_4_LOANNOPELL',
 'C150_L4_LOANNOPELL',
 'C150_4_NOLOANNOPELL',
 'C150_L4_NOLOANNOPELL',
 'C150_L4_PELL_POOLED',
 'C150_4_PELL_POOLED',
 'C150_L4_PELL_POOLED_SUPP',
 'C150_4_PELL_POOLED_SUPP']

In [15]:
[col for col in df.columns if "GRAD" in col]

['GRAD_DEBT_MDN',
 'GRAD_DEBT_N',
 'GRAD_DEBT_MDN10YR',
 'PCT_GRAD_PROF',
 'GRAD_DEBT_MDN_SUPP',
 'GRAD_DEBT_MDN10YR_SUPP',
 'GRADS']

In [16]:
[col for col in df.columns if "MD_EARN" in col]

['MD_EARN_WNE_P10',
 'MD_EARN_WNE_P6',
 'MD_EARN_WNE_P8',
 'MD_EARN_WNE_INC1_P6',
 'MD_EARN_WNE_INC2_P6',
 'MD_EARN_WNE_INC3_P6',
 'MD_EARN_WNE_INDEP1_P6',
 'MD_EARN_WNE_INDEP0_P6',
 'MD_EARN_WNE_MALE0_P6',
 'MD_EARN_WNE_MALE1_P6',
 'MD_EARN_WNE_INC1_P8',
 'MD_EARN_WNE_INC2_P8',
 'MD_EARN_WNE_INC3_P8',
 'MD_EARN_WNE_INDEP1_P8',
 'MD_EARN_WNE_INDEP0_P8',
 'MD_EARN_WNE_MALE0_P8',
 'MD_EARN_WNE_MALE1_P8',
 'MD_EARN_WNE_INC1_P10',
 'MD_EARN_WNE_INC2_P10',
 'MD_EARN_WNE_INC3_P10',
 'MD_EARN_WNE_INDEP1_P10',
 'MD_EARN_WNE_INDEP0_P10',
 'MD_EARN_WNE_MALE0_P10',
 'MD_EARN_WNE_MALE1_P10',
 'MD_EARN_WNE_1YR',
 'MD_EARN_WNE_4YR',
 'MD_EARN_WNE_5YR',
 'MD_EARN_WNE_P7',
 'MD_EARN_WNE_INC1_P7',
 'MD_EARN_WNE_INC2_P7',
 'MD_EARN_WNE_INC3_P7',
 'MD_EARN_WNE_INDEP1_P7',
 'MD_EARN_WNE_INDEP0_P7',
 'MD_EARN_WNE_MALE0_P7',
 'MD_EARN_WNE_MALE1_P7',
 'MD_EARN_WNE_P9',
 'MD_EARN_WNE_INC1_P9',
 'MD_EARN_WNE_INC2_P9',
 'MD_EARN_WNE_INC3_P9',
 'MD_EARN_WNE_INDEP0_P9',
 'MD_EARN_WNE_INDEP1_P9',
 'MD_EARN_WNE_MALE0_P9',
 'MD_EARN_WNE_MALE1_P9',
 'MD_EARN_WNE_P11',
 'MD_EARN_WNE_INC1_P11',
 'MD_EARN_WNE_INC2_P11',
 'MD_EARN_WNE_INC3_P11',
 'MD_EARN_WNE_INDEP0_P11',
 'MD_EARN_WNE_INDEP1_P11',
 'MD_EARN_WNE_MALE0_P11',
 'MD_EARN_WNE_MALE1_P11']

In [17]:
[col for col in df.columns if "DEBT_MDN" in col]

['DEBT_MDN',
 'GRAD_DEBT_MDN',
 'WDRAW_DEBT_MDN',
 'LO_INC_DEBT_MDN',
 'MD_INC_DEBT_MDN',
 'HI_INC_DEBT_MDN',
 'DEP_DEBT_MDN',
 'IND_DEBT_MDN',
 'PELL_DEBT_MDN',
 'NOPELL_DEBT_MDN',
 'FEMALE_DEBT_MDN',
 'MALE_DEBT_MDN',
 'FIRSTGEN_DEBT_MDN',
 'NOTFIRSTGEN_DEBT_MDN',
 'GRAD_DEBT_MDN10YR',
 'DEBT_MDN_SUPP',
 'GRAD_DEBT_MDN_SUPP',
 'GRAD_DEBT_MDN10YR_SUPP']

In [18]:
[col for col in df.columns if "ADM_RATE" in col]

['ADM_RATE', 'ADM_RATE_ALL', 'ADM_RATE_SUPP']

In [19]:
[col for col in df.columns if "STUFACRAT" in col]

[]

In [20]:
[col for col in df.columns if "FAC" in col]

['AVGFACSAL', 'PFTFAC', 'STUFACR']

In [21]:
[col for col in df.columns if "RAT" in col]

['ADM_RATE', 'ADM_RATE_ALL', 'POVERTY_RATE', 'UNEMP_RATE', 'ADM_RATE_SUPP']

In [22]:
dashboard_df = df[
    [
        "INSTNM",
        "STABBR",
        "UGDS",
        "ADM_RATE",
        "RET_FT4",
        "C150_4",
        "MD_EARN_WNE_P10",
        "DEBT_MDN"
    ]
]

In [23]:
dashboard_df.head()

,INSTNM,STABBR,UGDS,ADM_RATE,RET_FT4,C150_4,MD_EARN_WNE_P10,DEBT_MDN
0,Alabama A & M University,AL,6124.0,0.5795,0.6989,0.2403,40628.0,16600
1,University of Alabama at Birmingham,AL,11635.0,0.8818,0.8009,0.6423,54501.0,15832
2,Amridge University,AL,241.0,NaN,NaN,1.0000,37621.0,13385
3,University of Alabama in Huntsville,AL,6591.0,0.6857,0.8425,0.6429,61767.0,13905
4,Alabama State University,AL,3477.0,0.9755,0.6975,0.3034,34502.0,17500

In [24]:
dashboard_df.shape

(6322, 8)

In [25]:
dashboard_df.columns = [
    "Institution",
    "State",
    "Enrollment",
    "Admission_Rate",
    "Retention_Rate",
    "Graduation_Rate",
    "Median_Earnings",
    "Median_Debt"
]

In [27]:
dashboard_df.head()

,Institution,State,Enrollment,Admission_Rate,Retention_Rate,Graduation_Rate,Median_Earnings,Median_Debt
0,Alabama A & M University,AL,6124.0,0.5795,0.6989,0.2403,40628.0,16600
1,University of Alabama at Birmingham,AL,11635.0,0.8818,0.8009,0.6423,54501.0,15832
2,Amridge University,AL,241.0,NaN,NaN,1.0000,37621.0,13385
3,University of Alabama in Huntsville,AL,6591.0,0.6857,0.8425,0.6429,61767.0,13905
4,Alabama State University,AL,3477.0,0.9755,0.6975,0.3034,34502.0,17500

In [28]:
dashboard_df.isnull().sum()

Institution           0
State                 0
Enrollment          735
Admission_Rate     4395
Retention_Rate     4248
Graduation_Rate    4039
Median_Earnings    1149
Median_Debt         245
dtype: int64

In [29]:
dashboard_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6322 entries, 0 to 6321
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Institution      6322 non-null   object
 1   State            6322 non-null   object
 2   Enrollment       5587 non-null   float64
 3   Admission_Rate   1927 non-null   float64
 4   Retention_Rate   2074 non-null   float64
 5   Graduation_Rate  2283 non-null   float64
 6   Median_Earnings  5173 non-null   float64
 7   Median_Debt      6077 non-null   object
dtypes: float64(5), object(3)
memory usage: 395.3+ KB

In [30]:
dashboard_df["Median_Debt"].unique()[:20]

array(['16600', '15832', '13385', '13905', '17500', '17986', '5500',
       '14861', '13119', '17750', '5900', '13000', '15000', 'PS', '6100',
       '8200', '11756', '20000', '14000', '4500'], dtype=object)

In [32]:
dashboard_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6322 entries, 0 to 6321
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Institution      6322 non-null   object
 1   State            6322 non-null   object
 2   Enrollment       5587 non-null   float64
 3   Admission_Rate   1927 non-null   float64
 4   Retention_Rate   2074 non-null   float64
 5   Graduation_Rate  2283 non-null   float64
 6   Median_Earnings  5173 non-null   float64
 7   Median_Debt      5169 non-null   float64
dtypes: float64(6), object(2)
memory usage: 395.3+ KB

In [34]:
dashboard_df.head()

,Institution,State,Enrollment,Admission_Rate,Retention_Rate,Graduation_Rate,Median_Earnings,Median_Debt
0,Alabama A & M University,AL,6124.0,57.95,69.89,24.03,40628.0,16600.0
1,University of Alabama at Birmingham,AL,11635.0,88.18,80.09,64.23,54501.0,15832.0
2,Amridge University,AL,241.0,NaN,NaN,100.00,37621.0,13385.0
3,University of Alabama in Huntsville,AL,6591.0,68.57,84.25,64.29,61767.0,13905.0
4,Alabama State University,AL,3477.0,97.55,69.75,30.34,34502.0,17500.0

In [35]:
clean_df = dashboard_df.copy()

In [36]:
clean_df.to_csv(
    "projects/student_success_dashboard/data/student_success_clean.csv",
    index=False
)

In [37]:
import os

os.listdir("projects/student_success_dashboard/data")

['Most-Recent-Cohorts-Institution.csv', 'student_success_clean.csv']

In [38]:
dashboard_df.head()

,Institution,State,Enrollment,Admission_Rate,Retention_Rate,Graduation_Rate,Median_Earnings,Median_Debt
0,Alabama A & M University,AL,6124.0,57.95,69.89,24.03,40628.0,16600.0
1,University of Alabama at Birmingham,AL,11635.0,88.18,80.09,64.23,54501.0,15832.0
2,Amridge University,AL,241.0,NaN,NaN,100.00,37621.0,13385.0
3,University of Alabama in Huntsville,AL,6591.0,68.57,84.25,64.29,61767.0,13905.0
4,Alabama State University,AL,3477.0,97.55,69.75,30.34,34502.0,17500.0

In [39]:
clean_df = dashboard_df.copy()

clean_df.to_csv(
    "projects/student_success_dashboard/data/student_success_clean.csv",
    index=False
)

In [40]:
import os
os.listdir("projects/student_success_dashboard/data")

['Most-Recent-Cohorts-Institution.csv', 'student_success_clean.csv']

In [41]:
import sqlite3

In [42]:
conn = sqlite3.connect(
    "projects/student_success_dashboard/student_success.db"
)

In [43]:
clean_df.to_sql(
    "student_metrics",
    conn,
    if_exists="replace",
    index=False
)

6322

In [44]:
query = """
SELECT *
FROM student_metrics
LIMIT 5
"""

pd.read_sql(query, conn)

,Institution,State,Enrollment,Admission_Rate,Retention_Rate,Graduation_Rate,Median_Earnings,Median_Debt
0,Alabama A & M University,AL,6124.0,57.95,69.89,24.03,40628.0,16600.0
1,University of Alabama at Birmingham,AL,11635.0,88.18,80.09,64.23,54501.0,15832.0
2,Amridge University,AL,241.0,NaN,NaN,100.00,37621.0,13385.0
3,University of Alabama in Huntsville,AL,6591.0,68.57,84.25,64.29,61767.0,13905.0
4,Alabama State University,AL,3477.0,97.55,69.75,30.34,34502.0,17500.0

In [45]:
query = """
SELECT ROUND(AVG(Graduation_Rate),2)
AS Avg_Graduation_Rate
FROM student_metrics
"""

pd.read_sql(query, conn)

   Avg_Graduation_Rate
0                52.05

In [46]:
query = """
SELECT ROUND(AVG(Retention_Rate),2)
AS Avg_Retention_Rate
FROM student_metrics
"""

pd.read_sql(query, conn)

   Avg_Retention_Rate
0               73.83

In [47]:
query = """
SELECT SUM(Enrollment)
AS Total_Enrollment
FROM student_metrics
"""

pd.read_sql(query, conn)

   Total_Enrollment
0        14484370.0

In [48]:
query = """
SELECT
    State,
    ROUND(SUM(Enrollment),0) AS Total_Enrollment
FROM student_metrics
GROUP BY State
ORDER BY Total_Enrollment DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  State  Total_Enrollment
0    CA         2158168.0
1    TX         1239434.0
2    FL          857173.0
3    NY          800389.0
4    AZ          511703.0
5    PA          469126.0
6    IL          467912.0
7    OH          429559.0
8    GA          427018.0
9    NC          422418.0

In [49]:
query = """
SELECT
    Institution,
    Graduation_Rate
FROM student_metrics
WHERE Graduation_Rate IS NOT NULL
ORDER BY Graduation_Rate DESC
LIMIT 10
"""

pd.read_sql(query, conn)

                                Institution  Graduation_Rate
0                        Amridge University            100.0
1                        Lincoln University            100.0
2                 Pacific States University            100.0
3  Shasta Bible College and Graduate School            100.0
4         St. John Vianney College Seminary            100.0
5                       Divine Word College            100.0
6                         St Luke's College            100.0
7             Laboure College of Healthcare            100.0
8                               Cox College            100.0
9          Cleveland University-Kansas City            100.0

In [50]:
query = """
SELECT
    Institution,
    Median_Earnings
FROM student_metrics
WHERE Median_Earnings IS NOT NULL
ORDER BY Median_Earnings DESC
LIMIT 10
"""

pd.read_sql(query, conn)

                                         Institution  Median_Earnings
0              Massachusetts Institute of Technology         143372.0
1                          Samuel Merritt University         143238.0
2       Philadelphia College of Osteopathic Medicine         138767.0
3                                Harvey Mudd College         138687.0
4  University of Health Sciences and Pharmacy in ...         137047.0
5     Albany College of Pharmacy and Health Sciences         131426.0
6             Franklin W Olin College of Engineering         129455.0
7                 California Institute of Technology         128566.0
8                                   MCPHS University         125557.0
9                                Stanford University         124080.0

In [51]:
query = """
SELECT
    State,
    ROUND(AVG(Graduation_Rate),2) AS Avg_Graduation_Rate,
    ROUND(AVG(Retention_Rate),2) AS Avg_Retention_Rate,
    ROUND(AVG(Median_Earnings),0) AS Avg_Earnings
FROM student_metrics
GROUP BY State
ORDER BY Avg_Graduation_Rate DESC
"""

pd.read_sql(query, conn)

   State  Avg_Graduation_Rate  Avg_Retention_Rate  Avg_Earnings
0     MA                66.68               79.76       59509.0
1     RI                66.54               82.45       56328.0
2     CT                64.88               80.47       55894.0
3     IA                63.06               73.17       44074.0
4     VT                62.36               80.26       50930.0
5     CA                58.48               78.06       47512.0
6     PA                57.94               78.34       50603.0
7     ME                57.63               73.66       48802.0
8     VA                57.60               78.62       45018.0
9     MN                57.51               72.86       48091.0
10    NH                57.37               77.38       53440.0
11    NY                56.33               79.59       52170.0
12    MD                55.76               78.18       46300.0
13    WI                55.60               73.18       44793.0
14    MI                55.55               76.70       39232.0
15    IL                55.21               73.62       44167.0
16    OR                55.15               81.81       43494.0
17    FL                53.58               69.48       39041.0
18    IN                53.41               74.80       45200.0
19    DC                52.83               80.57       53594.0
20    ID                52.45               71.31       34305.0
21    MO                52.41               70.38       43627.0
22    NE                52.18               75.71       47499.0
23    NJ                51.36               77.21       48744.0
24    NC                51.19               71.81       39610.0
25    UT                50.55               71.14       38895.0
26    KY                50.43               72.89       37668.0
27    TN                49.78               69.81       40474.0
28    MS                48.34               72.91       33568.0
29    CO                47.94               69.25       43913.0
30    SC                47.29               70.72       39470.0
31    KS                46.62               65.88       44115.0
32    WA                46.40               76.57       49766.0
33    OH                46.40               69.36       43006.0
34    WV                46.04               64.84       38019.0
35    MT                45.36               70.96       38058.0
36    TX                45.23               69.41       40558.0
37    LA                45.05               72.06       36034.0
38    AR                44.65               65.93       35151.0
39    PR                44.43               73.81       24016.0
40    DE                43.88               58.99       44130.0
41    AL                43.30               68.18       40439.0
42    WY                43.17               68.13       40811.0
43    ND                43.00               76.22       42678.0
44    GU                42.82               88.31       28223.0
45    SD                42.81               74.62       43842.0
46    HI                42.04               72.79       43423.0
47    GA                40.76               67.09       40545.0
48    MP                40.74               73.33       27836.0
49    AK                40.39               73.46       43318.0
50    OK                40.10               68.40       37292.0
51    AZ                38.60               61.31       44196.0
52    NV                38.03               74.73       45794.0
53    NM                37.05               57.87       38684.0
54    FM                34.08               40.00       24651.0
55    AS                32.41                 NaN       30087.0
56    VI                28.23               68.59       38681.0
57    MH                18.37                 NaN           NaN
58    PW                  NaN                 NaN       29898.0

In [52]:
query = """
SELECT
    Institution,
    Enrollment,
    Graduation_Rate,
    Retention_Rate,
    Median_Earnings
FROM student_metrics
WHERE Institution LIKE '%Maryland%'
   OR Institution LIKE '%Towson%'
   OR Institution LIKE '%Morgan%'
   OR Institution LIKE '%Baltimore County%'
"""

pd.read_sql(query, conn)

,Institution,Enrollment,Graduation_Rate,Retention_Rate,Median_Earnings
0,Morgan Community College,634.0,44.58,NaN,39429.0
1,Robert Morgan Educational Center and Technical...,1045.0,NaN,NaN,37543.0
2,Allegany College of Maryland,1831.0,NaN,NaN,38476.0
3,College of Southern Maryland,4512.0,NaN,NaN,44435.0
4,Aveda Institute-Maryland,77.0,NaN,NaN,21250.0
5,Loyola University Maryland,3869.0,79.19,87.11,82652.0
6,University of Maryland Global Campus,49664.0,33.33,55.38,65287.0
7,University of Maryland Baltimore,958.0,NaN,NaN,88174.0
8,University of Maryland-Baltimore County,10701.0,70.01,85.05,69960.0
9,University of Maryland-College Park,30760.0,88.59,96.20,82860.0
10,Maryland Institute College of Art,1189.0,72.24,83.39,45212.0
11,University of Maryland Eastern Shore,2391.0,35.33,61.79,47697.0
12,Fortis Institute-Towson,354.0,NaN,NaN,36368.0
13,Morgan State University,9019.0,40.87,73.34,50698.0
14,Notre Dame of Maryland University,709.0,50.00,72.77,65344.0
15,Maryland Beauty Academy of Essex,35.0,NaN,NaN,20445.0
16,St. Mary's College of Maryland,1603.0,69.95,85.75,60110.0
17,Towson University,16136.0,69.46,82.77,64390.0
18,Maryland University of Integrative Health,NaN,NaN,NaN,NaN
19,Morgantown Beauty College Inc,68.0,NaN,NaN,22230.0
20,West Virginia Junior College-Morgantown,673.0,71.11,NaN,31912.0
21,Strayer University-Maryland,1043.0,37.50,100.00,40092.0
22,Community College of Baltimore County,13872.0,NaN,NaN,43729.0
23,Ross College-Morgantown,30.0,NaN,NaN,30481.0